name: deploy
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Setup venv
      run: python -m venv venv
    - name: Setup PyYAML
      run: venv/bin/pip install pyyaml
    - name: Generate Copypasta JSON
      run: venv/bin/python generate_copypasta.py
    - name: Archive Files
      run: tar cvzf archive.tar.gz index.html copypasta.json
    - name: Artifact
      uses: actions/upload-artifact@v3
      with:
        name: github-pages
        path: archive.tar.gz
        if-no-files-found: error
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
