name: deploy
on:
  push:
    branches: master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Setup venv
      run: python -m venv venv
    - name: Setup PyYAML
      run: venv/bin/pip install pyyaml
    - name: Generate Copypasta JSON
      run: venv/bin/python generate_copypasta.py
    - name: Archive Files
      run: tar --dereference --hard-dereference --directory $GITHUB_WORKSPACE -cvf artifact.tar index.html copypasta.json
    - name: Artifact
      uses: actions/upload-artifact@v3
      with:
        name: github-pages
        path: artifact.tar
        if-no-files-found: error
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v2
